config/routes.rb
CodersFh::Application.routes.draw do

 resources :users, controller: :idea_owners
 post '/login' => 'sessions#new'
 get '/logout' => 'sessions#destroy'
 get '/auth/:provider/callback' => 'sessions#github_auth'
 get 'auth/failure' => redirect('/')

 get '/about' => 'about#index'

 post 'wizard/update_user/:id', :to => 'wizard#update_user', :as => "wizard_update_user"
 post 'wizard/create_user', :to => 'wizard#create_user', :as => "wizard_create_user"
 post 'wizard/create_project', :to => 'wizard#create_project', :as => "wizard_create_project"
 post 'wizard/update_project/:id', :to => 'wizard#update_project', :as => "wizard_update_project"
 get 'wizard/review/:id', :to => 'wizard#review', :as => "wizard_review"
 get '/wizard', :to => 'wizard#new', :as => "new_wizard"

 resources :developers
 get 'dashboard/:id', :to => 'developers#dashboard', :as => "dashboard"

 resources :projects do
   resources :collaborations do
    member do
      get '/assign' => 'collaborations#assign'
    end
   end
 end

 root :to => 'welcome#index'


end

app/models/idea_owner.rb
class IdeaOwner < ActiveRecord::Base
  attr_accessible :account_id, :password

  has_secure_password

  belongs_to :account
  has_one :project, :foreign_key => :creator_id
  has_many :received_feedbacks, :as => :receiver, :class_name => "Feedback"
  has_many :given_feedbacks, :as => :author, :class_name => "Feedback"

  
  def name
    account.name
  end

  def email
    account.email
  end

  def location
    account.location
  end

  def organization
    account.organization
  end

end

app/controllers/idea_owners_controller.rb
class IdeaOwnersController < ApplicationController

  def show
    @project = current_user.project
    @feedbacks = current_user.received_feedbacks
  end

  def edit
  	@user = IdeaOwner.find_by_id(current_user.id)
  	@account = @user.account
  end

  def update
  	@user = IdeaOwner.find_by_id(current_user.id)
  	@user.update_attributes(params[:idea_owner])
    @account = @user.account
  	@account.update_attributes(params[:account])
  	redirect_to user_path
  end


end

app/views/idea_owners/edit.html.erb
<div class="page-header">
  <div class="shine">
    <div class="container">
      <div class="row-fluid">
        <div class="span12">
          <div class="row-fluid">
            <div class="span12">
              <h1 class="welcome_to_dashboard">Edit Profile</h1>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="well" style="width:760px; margin: 20px auto;">
  <div id="rootwizard">
    <ul class="bwizard-steps" data-start="1">
      <li><a href="#tab1" data-toggle="tab" class="lead"> Edit your profile</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane" id="tab1">
          <br><p class="lead">
          Please edit the fields below, and click update to save the changes.</p>
          <%= form_for @user, :url => user_path, :method => "PUT" do |f| %>
              <%=fields_for @account do |a|%>
                <%= a.label :name, "Name" %>
                <%= a.text_field :name %>
                <%= a.label :email, "Email" %>
                <%= a.text_field :email, :class => "email"%>
                <%= a.label :organization, "Organization/Company"%>
                <%= a.text_field :organization%>
                <%= a.label :location, "Location"%>
                <%= a.text_field :location%>
              <%end%>
              <%= f.label :password, "Change Password" %>
              <%= f.password_field :password, :placeholder => "New password"%>
              <%= f.submit "Update", :class => "submit-changes" %>
          <%end%>
        </div>
    </div>  
  </div>
</div>

app/views/idea_owners/show.html.erb
<!-- ################-->
<!-- PAGE HEADER -->
<div class="page-header">
  <div class="shine">
    <div class="container">
      <div class="row-fluid">
        <div class="span12">
          <div class="row-fluid">
            <div class="span12">
              <h1 class="welcome_to_dashboard">Dashboard</h1>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<!-- PAGE HEADER -->

<!-- ################ -->
<!-- CONTENT CONTAINER-->
<!-- ################ -->
<!-- PAGE HEADER -->
<div class="container">
  <div class="row-fluid blog">
    <div class="span8">
      <div class="blog-post">
        <div class="">
		<span class="breadcrumb span3 lead">Current <br>Project </span>
           <div class="dd_buttons clearfix">

           
       <hr class="half">
          </div>
        </div>
       
         <div id="project-area" class="span10">
         <br><br>
        <ul id="tab-navigation" class="nav nav-tabs" data-tabs="tabs">
          <li class="active"><a href="#details" data-toggle="tab"> Details</a> </li>
          <li><a href="#team" data-toggle="tab"> Team </a> </li>
          <li><a href="#feedback" data-toggle="tab"> Feedback </a> </li>
        </ul>
      <div id="details" class="tab-pane active">
        <p><div class="lead"><%=@project.title.humanize%></div> </p>
        <p>
          PROJECT DESCRIPTION: <br>
          <%= @project.description.humanize %>
        </p>

        <p>
          CATEGORY: <br>
          <span class="project_category">
            <%= @project.category.name.humanize %>
          </span>
        </p>

        <p>
          STATUS: <br>
          <span class="project_status">
           <%= @project.status.humanize  %>
         </span>
        </p>
        <div class="button1">
        <%= button_to "Project Public View", project_path(current_user.project), :class => "btn btn-warning btn-small", :method => :get, :style => "color:black;" %>
      
        </div>
        <div class="button2">
        
         <%= button_to "Edit Your Project", edit_project_path(current_user.project),:id => 'edit-project', :class => "btn btn-warning btn-small", :method => :get, :style => "color:black;" %>
        
         </div>
        </div>

        <div id="team" class="tab-pane">
          <% if @project.pending_collaborations.any? || @project.assigned_collaborations.any? %>
          <% if @project.pending_collaborations.any? %>
            <% @project.pending_collaborations.each do |collaboration| %>
              <div class="pending-collab alert alert-info">
                <%= link_to collaboration.developer.name, developer_path(collaboration.developer) %> is interested in your project
                <% if @project.not_yet_assigned? %>
                  <%= link_to "Promote to team lead", assign_project_collaboration_path(@project,collaboration), :class => "btn btn-warning", :style => "color:black" %>
                <% end %>
                <%= mail_to "#{collaboration.developer.email}", 'Contact', subject: "Question Regarding #{@project.title}", :class => "btn btn-warning", :style => "color:black" %>
              </div>
            <% end %>
          <% end %>

          <% if @project.assigned_collaborations.any? %>
          <div class="assigned-collab clearfix">
            <h1 class="large-text">Assigned developers</h1>
            <ul class="list-group">
            <% @project.assigned_collaborations.each do |collaboration| %>
            <li class="developer">
             <span class="idea_owners_organization">
              <%= mail_to "#{collaboration.developer.email}", 'Contact', subject: "Question Regarding #{@project.title}", :class => "btn btn-warning", :style => "color:black" %>
              <b><%= link_to collaboration.developer.name, developer_path(collaboration.developer) %></b>(<%= collaboration.role.description %>)
            </span>
              </li>  
            <% end %>
              </ul>
            </div>
          <% end %>
          <%else%>
          It looks like you don't have any collaborators yet.  <br>
          In mean time, why don't you take a look at all of our <%=link_to "Developers", root_path, :class => "dev_link"%>, and contact one!
          <%end%>

        </div>

        <div id="feedback" class="tab-pane">
          <div class="row-fluid">
        <div class="line2 center">
          <h5 class="standart-h3title"><span>YOUR RECEIVED FEEDBACK</span></h5>
        </div>
        <%@feedbacks.each do |feedback|%>
        <ul class="l_tinynav2 widget-archive" id="nav2">

                    <li>Posted by <%=IdeaOwner.find(feedback.author_id).name%>
                  <i class="fa-icon-user"></i>
                  <span>|</span> <%=feedback.created_at%><br><%=feedback.comment%><br><br></li><%end%>
                    
                  </ul>
            <div class="new-feedback">
              <%if @project.complete? %>
              <%=button_tag "Give your developer feedback", :class=> "btn btn-warning btn-small feedback-btn", :method=>:get, :style => "color:black;" %>
              <%end%>
            </div>
        </div>
        </div>


         
        </div>
      </div><!--span 8-->

      <hr class="soften">
    </div><!--fluid blog-->
	<!-- END CONTENT SIDE -->
	<!-- SIDEBAR-->
    <div class="span4 side_bar">
		
	  <div class="row-fluid">
				<div class="line2 center">
					<h5 class="standart-h3title"><span>My Profile <%= link_to edit_user_path(current_user) do %></span>
					<div class="edit-profile"><br>
          			<i class = "icon-edit"></i>Edit your profile</div>
          			<% end %></h5>
				</div>
        <ul class="l_tinynav2 widget-archive" id="nav2">
									  <li style="margin-left:0px;"> <b>Name:</b> <%= current_user.name %></li><br>
									  <li style="margin-left:0px;"><b>Organization:</b> <%= current_user.organization %></li><br>
									  <li style="margin-left:0px;"><b>Email:</b> <%= current_user.email %></li><br>
									  <li style="margin-left:0px;"><b>Location:</b> <%= current_user.location %></li><br>									  
									</ul>
        </div>
        <BR><BR>
        
	
    </div>
	<!-- END SIDEBAR-->
  </div>
  <!-- END INNER ROW-FLUID -->
</div>
<!-- END CONTENT CONTAINER-->
</div>
<!-- END: MAIN-WRAPPER-->