config/routes.rb
CodersFh::Application.routes.draw do

 resources :users, controller: :idea_owners
 post '/login' => 'sessions#new'
 get '/logout' => 'sessions#destroy'
 get '/auth/:provider/callback' => 'sessions#github_auth'
 get 'auth/failure' => redirect('/')

 get '/about' => 'about#index'

 post 'wizard/update_user/:id', :to => 'wizard#update_user', :as => "wizard_update_user"
 post 'wizard/create_user', :to => 'wizard#create_user', :as => "wizard_create_user"
 post 'wizard/create_project', :to => 'wizard#create_project', :as => "wizard_create_project"
 post 'wizard/update_project/:id', :to => 'wizard#update_project', :as => "wizard_update_project"
 get 'wizard/review/:id', :to => 'wizard#review', :as => "wizard_review"
 get '/wizard', :to => 'wizard#new', :as => "new_wizard"

 resources :developers
 get 'dashboard/:id', :to => 'developers#dashboard', :as => "dashboard"

 resources :projects do
   resources :collaborations do
    member do
      get '/assign' => 'collaborations#assign'
    end
   end
 end

 root :to => 'welcome#index'


end

app/views/shared/_footer.html.erb
<!-- Footer
  ================================================== -->
  <footer class="footer">
    <div class="container">
      <div class="row-fluid">
        <div class="span12">
          <div class="row-fluid">
            
    
        </div> 
      </div>
    </div>
    
    <div class="row-fluid">
      <div class="span4">
        <h4 class="line3 center standart-h4title"><span>Navigation</span></h4>
        <ul class="footer-links">
          <li><%= link_to "Home", '/' %></li>
          <li> <%= link_to "Projects", projects_path %></li>
          <li><%= link_to "Developers", developers_path %></li>
          <li><%= link_to "About Us", about_path %></li>
        </ul>
      </div>

      <div class="span4">
        <h4 class="line3 center standart-h4title"><span>Our office</span></h4>
        <address>
          <strong>Coders for Humanity</strong><br>
          <i class="fa-icon-map-marker"></i> 351 West Hubbard Street, Suite 701<br>
          Chicago, Il 60654<br>
          <i class="fa-icon-phone-sign"></i> +1 971 263 1411 
          <div class="foot-line"></div>

        </address>
      </div>
      <div class="span4">
        <h4 class="line3 center standart-h4title"><span>Stay in touch</span></h4>
        
        <div class="widget_nav_menu"> 
          <ul class="socialIcons">
           <li class="facebook"><a href="https://www.facebook.com/coders4humanity">facebook </a></li>
           <li class="twitter"><a href="https://twitter.com/Coders4Humanity">twitter</a></li>
            <li class="googleplus"><a href="https://plus.google.com/b/103046130956673553891/103046130956673553891/posts">googleplus</a></li>
            <li class="skype"><a href="skype:CodersForHumanity?call">skype</a></li>
            <li class="youtube"><a href="#">youtube</a></li>
          </ul>
        </div>
      </div>
    </div>
    <hr class="half1 copyhr">
    <div class="row-fluid copyright">
      <div class="span12 center">Copyright &copy; 2013. Coders for Humanity</div>
    </div>
  </div>
</footer>
<!-- END FOOTER -->
</div>

app/views/shared/_header.html.erb
<!-- ################-->
<!-- START TOP MENU -->
<!-- ################-->
<div class="nav-reaction">
  <div class="navbar navbar-static-top"> 
    <!-- navbar-fixed-top -->
    <div class="navbar-inner">
      <div class="home_page_container"> <a class="brand" href="/"> 
        <%= image_tag "logo2.gif" %>
        <span id="homepage_header">Coders for Humanity</span></a>
        <div id="main-nav">
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li><%= link_to 'About Us', about_path %></li>
              <li><%= link_to 'Projects', projects_path %></li>
              <% if current_user %>
                <li><%= link_to 'My Dashboard', idea_owner? ? user_path(current_user) : dashboard_path(current_user) %></li>
              <% else %>
                <li><%= link_to 'Get started', new_wizard_path %></li>
              <% end %>

              <% if current_user %>
                <li><%= link_to 'Sign out', logout_path %></li>
              <% else %>
              <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign in</a>
                <ul class="dropdown-menu">
                  <li>
                    <div style="padding: 15px; padding-bottom: 0px;">
                     <form method="post" action="login" accept-charset="UTF-8">
                      <input style="margin-bottom: 15px;" type="text" placeholder="Email" id="email" name="email">
                      <input style="margin-bottom: 15px;" type="password" placeholder="Password" id="password" name="password">
                      <input style="float: left; margin-right: 10px;" type="checkbox" name="remember-me" id="remember-me" value="1">
                      <label class="string optional" for="sign-in"> Remember me</label>
                      <input class="btn btn-info btn-block" type="submit" id="sign-in" value="Sign In">
                    </form>
                    <form method='get' action='/wizard'>
                      <label style="text-align:center;margin-top:5px">Don't Have an Account?</label>
                      <input class="btn btn-info btn-block" type="submit" id="sign-up" value="Sign Up">
                    </form>
                    <form method="get" action="/auth/github">
                      <label style="text-align:center;margin-top:5px">Are you a Developer?</label>
                      <input class="btn btn-primary btn-block" type="submit" id="sign-in-google" value="Sign In with Github">
                    </form>
                  </div>
                </li>
              </ul>
            </li>
            <% end %>
          </ul>
        </ul>
      </div>
    </div>
  </div>
</div>
</div>
</div>

app/views/shared/_home_header.html.erb
  <!-- START HEADER headertop -->
  <div class="headertop needhead">
    <!-- BLURED BACKGROUND-->
    <div class="action-banner-bg"></div>
    <!-- END BLURED BACKGROUND-->

    <!-- PIXEL BG DOTTS UNDER BLURED BACKGROUND-->
    <div class="action-banner-bg-top"></div>
    <!-- END PIXEL BG DOTTS UNDER BLURED BACKGROUND-->

<!-- ################-->
<!-- START TOP MENU -->
<!-- ################-->
<div class="nav-reaction">
  <div class="navbar navbar-static-top"> 
    <!-- navbar-fixed-top -->
    <div class="navbar-inner">
      <div class="home_page_container"> <a class="brand" href="/"> 
        <%= image_tag "logo2.gif" %>
        <span id="homepage_header">Coders for Humanity</span></a>
        <div id="main-nav">
          <div class="nav-collapse collapse">
            <ul class="nav">

              <li><%= link_to 'About us', '#about_us', :class => "about_us_navbar" %></li>
              <li><%= link_to 'Projects', '#projects_home', :class => "projects_navbar" %></li>
              <% if current_user %>
                <li><%= link_to 'My Dashboard', idea_owner? ? user_path(current_user) : dashboard_path(current_user) %></li>
              <% else %>
                <li><%= link_to 'Get started', new_wizard_path %></li>
              <% end %>

              <% if current_user %>
                <li><%= link_to 'Sign out', logout_path %></li>
              <% else %>
              <li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown">Sign in</a>
                <ul class="dropdown-menu">
                  <li>
                    <div style="padding: 15px; padding-bottom: 0px;">
                     <form method="post" action="login" accept-charset="UTF-8">
                      <input style="margin-bottom: 15px;" type="text" placeholder="Email" id="email" name="email">
                      <input style="margin-bottom: 15px;" type="password" placeholder="Password" id="password" name="password">
                      <input style="float: left; margin-right: 10px;" type="checkbox" name="remember-me" id="remember-me" value="1">
                      <label class="string optional" for="sign-in"> Remember me</label>
                      <input class="btn btn-info btn-block" type="submit" id="sign-in" value="Sign In">
                    </form>
                    <form method='get' action='/wizard'>
                      <label style="text-align:center;margin-top:5px">Dont Have an Account?</label>
                      <input class="btn btn-info btn-block" type="submit" id="sign-up" value="Sign Up">
                    </form>
                    <form method="get" action="/auth/github">
                      <label style="text-align:center;margin-top:5px">Are you a Developer?</label>
                      <input class="btn btn-primary btn-block" type="submit" id="sign-in-google" value="Sign In with Github">
                    </form>
                  </div>
                </li>
              </ul>
            </li>
            <% end %>
          </ul>
        </ul>
      </div>
    </div>
  </div>
</div>
</div>
</div>

app/views/shared/_project.html.erb
<div class="blog-post">
  <h2 class="standart-h2title"><%= @project.title %></h2>

  <p class="meta-blog clearfix" style='text-transform: capitalize' >
    <i class="icon-user"></i> Posted By: <%= @project.creator.name %> |  
    <i class="icon-envelope"></i> <a href="mailto:<%= @project.creator.email %>?Subject=Coders%20for%20Humanity:%20Interest%20in%20your%20Project">Contact by Email</a>  |
    <i class="icon-list"></i> Category: <%= @category %> |
    <i class="icon-user"></i> Project status: <%= @project.status %>
  </p>
  <div class="dd_buttons clearfix">
  </div>
  <h2 class='big-text'>Description:</h2> <br> <h3><%= @project.description %></h3>
  <% if developer?%>
    <% if @project.pending_collaborations.map(&:developer).include?(current_user) %>
      <p style="color:tomato;text-align:center;">You have already requested to join this project</p>
    <% else %>
    <%= form_for [@project, Collaboration.new] do |f| %>
      <input type="submit" class="btn btn-lg btn-warning" value="Collaborate">
    <% end %>
    <% end %>
  <% end %>
</div>

app/views/shared/_project_submission.html.erb
<div class="blog-post wizard_partial span7">
  <div class="span6"><h2 class="standart-h2title center">Project: <%= @project.title %></h2>
  </div>
  <p class="meta-blog clearfix" style='text-transform: capitalize' >
    <i class="icon-user"></i> Posted By: <%= @project.creator.name %> | 
    <i class="icon-envelope"></i> <%= link_to 'Contact' %> | 
    <i class="icon-list"></i> Category: <%= @project.category.name %> | 
    <i class="icon-user"></i> Project status: <%= @project.status %>
  </p>
  <div class="dd_buttons clearfix">
  </div>
  <h2 class='big-text'>Description:</h2> <br> <h3><%= @project.description %></h3>
</div>