config/routes.rb
CodersFh::Application.routes.draw do

 resources :users, controller: :idea_owners
 post '/login' => 'sessions#new'
 get '/logout' => 'sessions#destroy'
 get '/auth/:provider/callback' => 'sessions#github_auth'
 get 'auth/failure' => redirect('/')

 get '/about' => 'about#index'

 post 'wizard/update_user/:id', :to => 'wizard#update_user', :as => "wizard_update_user"
 post 'wizard/create_user', :to => 'wizard#create_user', :as => "wizard_create_user"
 post 'wizard/create_project', :to => 'wizard#create_project', :as => "wizard_create_project"
 post 'wizard/update_project/:id', :to => 'wizard#update_project', :as => "wizard_update_project"
 get 'wizard/review/:id', :to => 'wizard#review', :as => "wizard_review"
 get '/wizard', :to => 'wizard#new', :as => "new_wizard"

 resources :developers
 get 'dashboard/:id', :to => 'developers#dashboard', :as => "dashboard"

 resources :projects do
   resources :collaborations do
    member do
      get '/assign' => 'collaborations#assign'
    end
   end
 end

 root :to => 'welcome#index'


end

app/controllers/wizard_controller.rb
class WizardController < ApplicationController

  def new
    @user = IdeaOwner.new
    @account = Account.new
    @project = Project.new
    @categories = Category.all

    render 'wizard'
  end

  def create_user
    user = IdeaOwner.create(params[:idea_owner])
    user.create_account(params[:account])
    user.save

    session[:idea_owner_id] = user.id
    render :json => { :user_id => user.id}
  end

  def update_user
    user = IdeaOwner.find(params[:id])
    user.update_attributes(params[:idea_owner])
    user.account.update_attributes(params[:account])

    render :json => { :user_id => user.id }
  end

  def create_project
    project = current_user.create_project(params[:project])


    render :json => { :project_id => project.id }
  end

  def update_project
    project = Project.find(params[:id])
    project.update_attributes(params[:project])

    render :json => { :project_id => @project.id }
  end

  def review
    @project = Project.find(params[:id])
    render 'review', layout: false
  end

end

app/views/wizard/review.html.erb
<br>
<br>

<p class="lead">
	Please review your submission; the text will appear on our Projects page as it does below.  Should you wish to edit your form please click 'Previous'.<br><br> 
	'Submit' will save all of your data and redirect you to your Dashboard. <br>
	<hr class="half"> 

	<%= render 'shared/project_submission'  %>

	<hr class="half"> 

	<hr class="half"> 

	<%= link_to "Submit", user_path, :style => '-moz-border-radius: 15px; -webkit-border-radius: 15px; border: 3px solid #009900; padding: 5px; text-decoration: none;', :class => "submit_button" %><br><br>

app/views/wizard/wizard.html.erb
<div class="page-header"> 
  <div class="shine">
    <div class="container">
      <div class="row-fluid">
        <div class="span12">
          <h1 class="welcome_to_dashboard">Sign Up / Create a Project</h1>
        </div>
      </div>
    </div>
  </div>
</div>
<!---- END IMAGE HEADER -->

<div class="wizard_container">
  <div class="well" style="width:800px; margin: 20px auto;">
    <div id="rootwizard">
      <ul class="bwizard-steps" data-start="1">
        <li><a href="#tab1" data-toggle="tab"><span class="label">1</span> Sign up</a></li>
        <li><a href="#tab2" data-toggle="tab"><span class="label">2</span> Select category </a></li>
        <li><a href="#tab3" data-toggle="tab"><span class="label">3</span> Details</a></li>
        <li><a href="#tab4" data-toggle="tab"><span class="label">4</span> Agreements</a></li>
        <li><a href="#tab5" data-toggle="tab"><span class="label">5</span> Review</a></li>
      </ul>
      <div class="tab-content">

        <div class="tab-pane" id="tab1"><br>
          <p class="lead">
            After signing up and posting your project details, developers will be able to review your challenge and connect with you to propose a technical solution.<br><br>
            To start the process, please create an account.<br><br>
            We promise to keep your contact information secure and free from spamming.<br><br>
            Alternatively, if you prefer, you may <%= link_to "continue browsing.", root_path, :class => 'click-me' %>
          </p>
          <%= form_for @user, :url => wizard_create_user_path, :method => 'POST' do |f| %>
            <%= fields_for @account do |a| %>
              <%= a.label :name, "Name" %>
              <%= a.text_field :name, :class => 'required' %>
              <%= a.label :email, "Email" %>
              <%= a.text_field :email, :class => "required email" %>
            <%end%>
            <%= f.label :password, "Password" %>
            <%= f.password_field :password, :class => "required" %>
          <% end %>
        </div>

        <div class="tab-pane" id="tab2">
          <% if @categories %>
            <div style="text-align:center; margin-top: 50px;">
              <%= form_for @project, :url => wizard_create_project_path , :html => {:id => "category_form"} do |f| %>
                <strong>
                  <%= f.label :category_id, "Select a category for your project"  %>
                </strong>
                <p>
                  <%= f.select :category_id,  options_from_collection_for_select(@categories, :id, :name), {:include_blank => true, :default => nil}, { :class => 'required' }  %>
                </p>
              <% end %>
            </div>
          <% end %>
        </div>

        <div class="tab-pane" id="tab3"><br>
          <p class="lead">
            To connect with the right web developer or team of developers, please tell us more about your challenge.  Your project will be viewable in our projects board and our community of developers will then engage in discussion with you to help iterate and plan your idea. <br><br>  <a id="sample_project_button" style='color: blue'>Click here</a> to see an example of the sort of detail that is helpful.
                <div id="sample_div" style="width:500px; margin: 20px auto; font-size:1.2em;"><br><h3>Project Example</h3><p><strong>Title:</strong><br>Build me a system I can use to catalogue and display the plants in my nursery</p><br><p><strong>Description:</strong><br>My current process involves taking a photo of each plant, printing the photo, and displaying it in a folder with a hand-written description.  Each time I stock a new plant I have to rearrange the order of the folder. Printing is expensive so I only have one folder to show my customers.</p></div>
          </p>
          <% if @project %>
            <%= form_for @project, :url => wizard_create_project_path do |f| %>
              <strong>
                <%= f.label :title, "Title" %>
              </strong>

              <small>
                In one sentence, please describe your challenge.
              </small><br>

              <%= f.text_field :title, :class => 'required', :style => "margin: 0px; width: 717px;" %>

              <strong>
                <%= f.label :description, "Description"%>
              </strong>

              <small >
                What are the steps in your current process?  What single task takes up the most time?  What task do you repeat most often?  What is biggest problem about the way you currently work?
              </small><br>

              <%= f.text_area :description, :class => 'required', :style => "margin: 0px; width: 717px; height: 180px;" %>
            <% end %>
          <% end %>
        </div>

        <div class="tab-pane" id="tab4"><br><br>
          <strong>Here are some guidelines to make the most of the relationship with your developers:</strong><br><br>
          <ul class="list-group">
            <li class="list-group-item">
              At the start of a collaboration, please provide your lead developer with details of your main point of contact who will answer any questions that arise during the process.<br><br>
            </li>
            <li class="list-group-item">
              I agree to not hold Coders for Humanity legally accountable for any agreements reached / work completed in relation to my posted project.  Any agreement made is solely between users of our platform.<br><br> 
            </li>
            <li class="list-group-item">
              Please mark your project as complete via your Dashboard, once you have a solution that you are happy with.<br><br>
            </li>
          </ul><br>

          <form name="user_agreement" action="agree_to_conditions" method="post">
            <input class='required' id="agreement" type="checkbox" name="agreement" value="false"> I agree to follow these guidelines.<br>
          </form>
        </div>

        <div class="tab-pane" id="tab5">
        </div>

        <ul class="pager wizard">
          <li class="previous">
            <a href="#">Previous</a>
          </li>
          <li class="next">
            <a id="next_button"ref="#">Next</a>
          </li>
        </ul>
      </div>
    </div>
  </div>
</div>